# Generated by Django 5.2.4 on 2025-09-08 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telegramuser_created_at_telegramuser_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='document_file_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='image_file_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='voice_file_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='core.telegramuser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.telegramuser'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
